In [1]:
import numpy as np

# 创建数组 a，从 1 到 19（不包含 19），步长为 1
a = np.arange(1, 19, 1)

# 创建数组 b，从 19 到 49（不包含 49），步长为 1
b = np.arange(19, 49, 1)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48]


In [2]:
# 利用reshape函数，将a形变为3×6的数组，保存为A
A = a.reshape(3, 6)

# 将b形变为5×6的数组，保存为B
B = b.reshape(5, 6)

print(A)
print(B)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [3]:
# 利用vstack将A和B数组进行垂直方向拼接，保存为C数组
C = np.vstack((A, B))

# 利用split对C数组在第2行分裂成两部分，将下半部分保存为D
D = np.split(C, [2])[1]

print(C)
print(D)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]
[[13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [4]:
# 对D提取第1行所有元素，保存为E
E = D[0, :]
print(E)

[13 14 15 16 17 18]


In [6]:
# 利用multiply.accumulate对E中所有元素依次求积，并保留最后一项作为E中的累计积保存为a1
a1 = np.multiply.accumulate(E)[-1]
print(a1)

13366080
